### ISSUE TITLE
`SessionId` instead of `Clientid` in type signature

### ISSUE THREAD

**Issue by SiriusStarr** [lamdera/auth#7]
`sendToFrontend : Auth.Common.SessionId -> toFrontend -> Cmd backendMsg`
should be 
`sendToFrontend : Auth.Common.ClientId -> toFrontend -> Cmd backendMsg`

When `SessionId` and `ClientId` stop being primitive aliases, this will cause compile errors.

https://github.com/lamdera/auth/blob/19d97e5da51fd79b4c40bf4b2fb542a8a0d600b3/src/Auth/Flow.elm#L115

**Comment by supermario** [comment]
Hey @SiriusStarr – thanks for the report!

The documentation at https://dashboard.lamdera.app/docs/wire#send-values-to-the-frontend has been updated to note both usages now.

In future this might get tightened up with specific functions and an opaque type perhaps, if we can simultaneously solve the `Dict comparable a` usability issue somehow, but for now it'll stay like this for ease.
